name: Unit Test

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unittest:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: swift package resolve
    - name: Pick xcode 16.2
      run: sudo xcode-select -s '/Applications/Xcode_16.2.app/Contents/Developer'
    - name: Run Tests on MacOS
      run: |
        swift build -v
        swift test -v
    - name: Run Tests on iPhone 16 Simulator (iOS 18.2)
      run: |
        xcodebuild test \
          -scheme 'Injection' \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
          -skipPackagePluginValidation